CREATE TABLE "todos" (
	"id" UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID() NOT NULL,
	"title" VARCHAR(500) NOT NULL,
	"description" VARCHAR(1000),
	"completed" BOOLEAN DEFAULT FALSE,
	"createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	"updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);